### ISSUE TITLE
Problem starting

### ISSUE THREAD

**Issue by KillAllSnitches** [juvian/discord-image-dupe#17]
i get this error on launch

PS C:\Users\zakis\Desktop\discord-image-dupe-master> node -r dotenv/config server.js
C:\Users\zakis\Desktop\discord-image-dupe-master\node_modules\depd\index.js:399
    throw new TypeError('argument fn must be a function')
    ^

TypeError: argument fn must be a function
    at Function.wrapfunction [as function] (C:\Users\zakis\Desktop\discord-image-dupe-master\node_modules\depd\index.js:399:11)
    at Object.<anonymous> (C:\Users\zakis\Desktop\discord-image-dupe-master\node_modules\express\lib\utils.js:70:37)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\zakis\Desktop\discord-image-dupe-master\node_modules\express\lib\application.js:24:19)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
PS C:\Users\zakis\Desktop\discord-image-dupe-master>

i have a file named .env with the proper paramaters specified

**Comment by juvian** [comment]
Yes its .env
Can you reach me out on discord? juvian#4621
